@echo off
echo [TEST] Starting Server...
start "Arcade Survivors Server" python server/server.py

echo [TEST] Waiting for server to initialize...
timeout /t 2 /nobreak > nul

echo [TEST] Starting Game Client...
bin\game.exe

echo [TEST] Cleaning up...
taskkill /FI "WINDOWTITLE eq Arcade Survivors Server*" /T /F > nul 2>&1
